version: '3.9'
services:
  api-gateway:
    container_name: api-gateway
    build:
      dockerfile: Dockerfile
      context: .
    hostname: api-gateway
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s
    networks:
      - shared-network

networks:
  shared-network:
    external: true

