version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: my-app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Монтирование Docker сокета
