spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/grafana/**]':
            allowedOrigins: "https://api-obshaga-service.ru"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - Content-Type
              - Authorization
              - X-Grafana-Org-Id
              - X-Grafana-Device-Id
              - Accept
            allowCredentials: true
      routes:
        - id: userservice
          uri: http://localhost:8081
          predicates:
            - Path=/users/**, /sessions/**, /roles/**
        - id: bookingsservice
          uri: http://localhost:8082
          predicates:
            - Path=/bookings/**
        - id: administrationservice
          uri: http://localhost:8083
          predicates:
            - Path=/balance/**, /documents/**
        - id: schedulesservice
          uri: http://localhost:8084
          predicates:
            - Path=/schedules/**, /responsibles/**
        - id: notificationservice
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**