server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret: WS5y43NO8hme4sbPyEgIcCaR7G5NgSXlXKyc159gLhloaNAP/28XZKPCQCCDd8vp3v1NJpIic4uMX0CVbPR7+A==

internal:
  secret: bbc1edb7448e4c177cc8519017ccfcfd8b23b87cc7abd735ac498a2b971670d6cd7f3f24679ba6212bc67ce2fe8f643fc4787071d407e31af2ca05ea28da709c
  lifetime: 10s

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, beans, trace
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true

spring:
  application:
    name: api-gateway
  profiles:
    active: "prod"

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/grafana/**]':
            allowedOrigins: "https://api-obshaga-service.ru"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - Content-Type
              - Authorization
              - X-Grafana-Org-Id
              - X-Grafana-Device-Id
              - Accept
            allowCredentials: true
      routes:
        - id: userservice
          uri: http://userservice:8080
          predicates:
            - Path=/users/**, /sessions/**, /roles/**
        - id: bookingsservice
          uri: http://bookingservice:8080
          predicates:
            - Path=/bookings/**
        - id: administrationservice
          uri: http://administrationservice:8080
          predicates:
            - Path=/balance/**, /documents/**
        - id: schedulesservice
          uri: http://schedulesservice:8080
          predicates:
            - Path=/schedules/**, /responsibles/**
        - id: notificationservice
          uri: http://notificationservice:8080
          predicates:
            - Path=/notifications/**
        - id: grafana
          uri: http://grafana.monitoring.svc.cluster.local:3000
          predicates:
            - Path=/grafana/**
          filters:
            - RewritePath=/grafana/(?<segment>.*), /grafana/${segment}

otlp:
  tracing:
    export-enabled: true
    endpoint: http://tempo.monitoring.svc.cluster.local:4317
    timeout: 5000
    service-name: api-gateway

rest:
  base-url:
    user-service: http://userservice:8080
    booking-service: http://bookingservice:8080
    schedule-service: http://schedulesservice:8080
    admin-service: http://administrationservice:8080