server:
  port: 8080

jwt:
  secret: WS5y43NO8hme4sbPyEgIcCaR7G5NgSXlXKyc159gLhloaNAP/28XZKPCQCCDd8vp3v1NJpIic4uMX0CVbPR7+A==

#spring:
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: userservice
#            uri: http://userservice:8080
#            predicates:
#              - Path=/users/**, /sessions/**  # Объединяем пути в один предикат
#          - id: bookingsservice
#            uri: http://bookingservice:8080
#            predicates:
#              - Path=/bookings/**
#          - id: administrationservice
#            uri: http://administrationservice:8080
#            predicates:
#              - Path=/balance/**, /documents/**





