apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      automountServiceAccountToken: false  # отключаем автоматическое монтирование, если не нужно
      containers:
        - name: gateway
          image: ghcr.io/tpabka251/gateway:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "0Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
